# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/PluginsPy/TemplateUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TemplatUI(object):
    def setupUi(self, TemplatUI):
        TemplatUI.setObjectName("TemplatUI")
        TemplatUI.resize(955, 560)
        self.verticalLayoutWidget = QtWidgets.QWidget(TemplatUI)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 931, 531))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.TLVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.TLVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.TLVerticalLayout.setObjectName("TLVerticalLayout")
        self.TLTemplateComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.TLTemplateComboBox.setObjectName("TLTemplateComboBox")
        self.TLVerticalLayout.addWidget(self.TLTemplateComboBox)
        self.TLGridLayout = QtWidgets.QGridLayout()
        self.TLGridLayout.setObjectName("TLGridLayout")
        self.TLVerticalLayout.addLayout(self.TLGridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.TLRegPlainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.TLRegPlainTextEdit.setObjectName("TLRegPlainTextEdit")
        self.horizontalLayout_3.addWidget(self.TLRegPlainTextEdit)
        self.TLVerticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.TLXAxisLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.TLXAxisLineEdit.setObjectName("TLXAxisLineEdit")
        self.horizontalLayout_4.addWidget(self.TLXAxisLineEdit)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.TLDataIndexLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.TLDataIndexLineEdit.setObjectName("TLDataIndexLineEdit")
        self.horizontalLayout_4.addWidget(self.TLDataIndexLineEdit)
        self.TLVerticalLayout.addLayout(self.horizontalLayout_4)
        self.TLInfoPlainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.TLInfoPlainTextEdit.setObjectName("TLInfoPlainTextEdit")
        self.TLVerticalLayout.addWidget(self.TLInfoPlainTextEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.TLRegexPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.TLRegexPushButton.setObjectName("TLRegexPushButton")
        self.horizontalLayout.addWidget(self.TLRegexPushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.TLVisualLogPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.TLVisualLogPushButton.setObjectName("TLVisualLogPushButton")
        self.horizontalLayout.addWidget(self.TLVisualLogPushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.TLGenPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.TLGenPushButton.setObjectName("TLGenPushButton")
        self.horizontalLayout.addWidget(self.TLGenPushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.TLVerticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(TemplatUI)
        QtCore.QMetaObject.connectSlotsByName(TemplatUI)
        TemplatUI.setTabOrder(self.TLTemplateComboBox, self.TLRegPlainTextEdit)
        TemplatUI.setTabOrder(self.TLRegPlainTextEdit, self.TLXAxisLineEdit)
        TemplatUI.setTabOrder(self.TLXAxisLineEdit, self.TLDataIndexLineEdit)
        TemplatUI.setTabOrder(self.TLDataIndexLineEdit, self.TLInfoPlainTextEdit)
        TemplatUI.setTabOrder(self.TLInfoPlainTextEdit, self.TLRegexPushButton)
        TemplatUI.setTabOrder(self.TLRegexPushButton, self.TLVisualLogPushButton)
        TemplatUI.setTabOrder(self.TLVisualLogPushButton, self.TLGenPushButton)

    def retranslateUi(self, TemplatUI):
        _translate = QtCore.QCoreApplication.translate
        TemplatUI.setWindowTitle(_translate("TemplatUI", "TemplateUI"))
        self.label.setText(_translate("TemplatUI", "  Regex:"))
        self.label_2.setText(_translate("TemplatUI", " X Axis:"))
        self.label_3.setText(_translate("TemplatUI", " DataIndex:"))
        self.TLRegexPushButton.setText(_translate("TemplatUI", "Regex"))
        self.TLVisualLogPushButton.setText(_translate("TemplatUI", "Visual Log"))
        self.TLGenPushButton.setText(_translate("TemplatUI", "Generate Template"))
